### ISSUE TITLE
le binaire dbmongo doit pouvoir s'exécuter en l'absence du code source

### ISSUE THREAD

**Issue by adrienjoly** [signaux-faibles/opensignauxfaibles#234]
## Problème

En lançant une opération `reduce` en prod, Pierre a obtenu une erreur `lstat: js/reduce.algo2 not found` (erreur approximative)

## Hypothèse

L'erreur serait due au fait que le code Go de cross-computation charge un fichier JSON depuis ce répertoire.

## Solution proposée

Faire en sorte que les fichiers JSON (y compris ceux employés par la validation) soient inclus dans le binaire, quitte à les bundler via un `go generate`.

- [x] fichier JSON cross-computation => PR #236 (fusionné)
- [x] fichiers JSON validation => PR #236 (fusionné)
- [x] autres: script diane, etc... (cf https://github.com/signaux-faibles/opensignauxfaibles/pull/236/files#diff-3e103440521ada06efd263ae09b259e5507e4b8f7408308dc227621ad9efa31eR29) => PR #238.
